name: Node.js CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: Install dependencies
        run: npm ci --only=production
      - name: Build Node.js site
        run: npm run build
      - name: Login to Nexus
        uses: docker/login-action@v3
        with:
          registry: docker.politcubes.com
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
      - name: Build Docker image
        run: docker build -t docker.politcubes.com/politcubes/wiki .
      - name: Push image to Nexus
        run: docker push docker.politcubes.com/politcubes/wiki
